server:
  port: 8083

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5432/postgres?currentShema=orders
    username: orders
    password: qwerty123
  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: password
    mode: native

app:basePath: /

active-mq:
  new-order-topic: OrderRequested