logging:
  level:
    org.hibernate.SQL: debug
    org.hibernate.type: trace

server:
  port: 8083
  servlet:
    context-path: '/order'

spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: jdbc:postgresql://localhost:5432/postgres?currentShema=orders
      username: orders
      password: qwerty123
    rabbitmq:
      host: localhost
      port: 5672
      username: rabbit
      password: rabbit
    redis:
      host: localhost
      port: 6379


app.basePath: /order
cart.url: http://localhost:8087/cart