spring:
    datasource:
      driver-class-name: 'org.postgresql.Driver'
      url: ${DB_URL}
      username: ${DB_USER}
      password: ${DB_PSW}
    rabbitmq:
      host: ${MQ_URL}
      port: ${MQ_PORT}
      username: ${MQ_USER}
      password: ${MQ_PSW}

app.basePath:
cart.url: ${CART_URL}

active-mq:
  OrderCreated-topic: OrderCreated
  OrderReady-topic: OrderReady
  OrderCanceled-topic: OrderCanceled
  OrderDone-topic: OrderDone

  SagaReserveProduct-topic: SagaReserveProduct
  SagaReserveProductRollback-topic: SagaReserveProductRollback
  ProductReserved-topic: ProductReserved
  NotEnoughProduct-topic: NotEnoughProduct
  ProductSold-topic: ProductSold

  SagaMakePayment-topic: SagaMakePayment
  SagaMakePaymentRollback-topic: SagaMakePaymentRollback
  PaymentSuccessful-topic: PaymentSuccessful
  PaymentRejected-topic: PaymentRejected

  SagaScheduleDelivery-topic: SagaScheduleDelivery
  SagaScheduleDeliveryRollback-topic: SagaScheduleDeliveryRollback
  DeliveryScheduled-topic: DeliveryScheduled
  DeliveryRejected-topic: DeliveryRejected

#настройка actuator
management:
  endpoints:
    web:
      exposure:
        include: '*'
  endpoint:
    health:
      show-details: always

---
#настройка для prometheus
management:
  metrics:
    distribution:
      percentiles[http.server.requests]: 0.5, 0.95, 0.99, 1
      percentiles-histogram[http.server.requests]: true