server:
  port: 8083
  servlet:
    context-path: '/order'

spring:
  datasource:
    driver-class-name: 'org.postgresql.Driver'
    url: jdbc:postgresql://localhost:5432/postgres?currentShema=orders
    username: orders
    password: qwerty123
  artemis:
    host: localhost
    port: 61616
    user: artemis
    password: password
    mode: native

app.basePath: /order
cart.url: http://localhost:8087/cart